/* Catálogo — 21 modelos, 115 sabores. Preços em BRL. */
const CATALOG = [
  { id: "ignite-v500", brand: "Ignite", model: "V500", puffs: 50000, puffsLabel: "50 mil puxadas", priceFrom: 230, priceTo: 194, dual: false, form: "cylinder", novo: true, flavors: [
    { name: "Uva ice", emoji: "🍇", key: "uva-ice" },
    { name: "Abacaxi ice", emoji: "🍍", key: "abacaxi-ice" },
    { name: "Blueberry ice", emoji: "🧊", key: "blueberry-ice" },
    { name: "Morango ice", emoji: "🍓", key: "morango-ice" },
    { name: "Melancia mix", emoji: "🍉", key: "melancia-mix" },
    { name: "Cool Menthol", emoji: "🧊", key: "cool-menthol" },
    { name: "Kiwi com açaí", emoji: "🥝🍇", key: "kiwi-com-acai" },
    { name: "Banana cereja", emoji: "🍌🍒", key: "banana-cereja" },
    { name: "Mango passion fruit", emoji: "🥭", key: "mango-passion-fruit" },
    { name: "Pêssego com uva", emoji: "🍑🍇", key: "pessego-com-uva" },
    { name: "Abacaxi com manga", emoji: "🍍🥭", key: "abacaxi-com-manga" },
    { name: "Maçã verde pêssego kiwi", emoji: "🍏🍑🥝", key: "maca-verde-pessego-kiwi" },
  ]},
  { id: "oxbar-50k", brand: "Oxbar", model: "50k Fumaça Invisível", puffs: 50000, puffsLabel: "50 mil puxadas", priceFrom: 229, priceTo: 179, dual: false, form: "cylinder", flavors: [
    { name: "Uva ice", emoji: "🍇", key: "uva-ice" },
    { name: "Icy mint", emoji: "🧊", key: "icy-mint" },
    { name: "Abacaxi ice", emoji: "🍍", key: "abacaxi-ice" },
    { name: "Melancia ice", emoji: "🍉", key: "melancia-ice" },
    { name: "Morango ice", emoji: "🍓", key: "morango-ice" },
    { name: "Morango uva", emoji: "🍓🍇", key: "morango-uva" },
    { name: "Morango kiwi", emoji: "🍓🥝", key: "morango-kiwi" },
    { name: "Passion fruit sour kiwi", emoji: "🥝", key: "passion-fruit-sour-kiwi" },
    { name: "Abacaxi kiwi dragon fruit", emoji: "🍍🥝", key: "abacaxi-kiwi-dragon-fruit" },
  ]},
  { id: "ignite-v400-ice-ultraslim", brand: "Ignite", model: "V400 Ice ULTRASLIM", puffs: 40000, puffsLabel: "40 mil puxadas", priceFrom: 220, priceTo: 179, dual: false, form: "ultraslim", novo: true, flavors: [
    { name: "Uva ice", emoji: "🍇", key: "uva-ice" },
    { name: "Mint ice", emoji: "🧊", key: "mint-ice" },
    { name: "Melancia ice", emoji: "🍉", key: "melancia-ice" },
    { name: "Morango ice", emoji: "🍓", key: "morango-ice" },
    { name: "Blueberry ice", emoji: "🧊", key: "blueberry-ice" },
    { name: "Melancia cereja", emoji: "🍉🍒", key: "melancia-cereja" },
    { name: "Morango com kiwi", emoji: "🍓🥝", key: "morango-com-kiwi" },
  ]},
  { id: "dinnerlady-galax", brand: "DinnerLady", model: "Galax", puffs: 60000, puffsLabel: "60 mil puxadas", priceFrom: 210, priceTo: 172, dual: false, form: "box", flavors: [
    { name: "Cherry", emoji: "🍒", key: "cherry" },
    { name: "Sour apple", emoji: "🍏", key: "sour-apple" },
    { name: "Miami mint", emoji: "🧊", key: "miami-mint" },
    { name: "Ultimate melon", emoji: "🍈", key: "ultimate-melon" },
  ]},
  { id: "elfbar-bc45k", brand: "Elfbar", model: "BC45K", puffs: 45000, puffsLabel: "45 mil puxadas", priceFrom: 200, priceTo: 169, dual: false, form: "box", novo: true, flavors: [
    { name: "Uva ice", emoji: "🍇", key: "uva-ice" },
    { name: "Miami mint", emoji: "🧊", key: "miami-mint" },
    { name: "Melancia ice", emoji: "🍉", key: "melancia-ice" },
    { name: "Maçã verde ice", emoji: "🍏", key: "maca-verde-ice" },
    { name: "Kiwi passion fruit guava", emoji: "🥝", key: "kiwi-passion-fruit-guava" },
  ]},
  { id: "ignite-shisha-40k", brand: "Ignite", model: "Shisha 40k", puffs: 40000, puffsLabel: "40 mil puxadas", priceFrom: 199, priceTo: 166, dual: false, form: "shisha", flavors: [
    { name: "White grape", emoji: "🍇", key: "white-grape" },
    { name: "Triple Mint", emoji: "🧊", key: "triple-mint" },
    { name: "Double Apple", emoji: "🍎", key: "double-apple" },
    { name: "Triple melon", emoji: "🍈", key: "triple-melon" },
    { name: "Blueberry lemonade", emoji: "🍋", key: "blueberry-lemonade" },
  ]},
  { id: "blacksheep-dual-tanque", brand: "BlackSheep", model: "Dual Tanque", puffs: 40000, puffsLabel: "40 mil puxadas", priceFrom: 189, priceTo: 166, dual: true, form: "dual", flavors: [
    { name: "Uva / Menthol", emoji: "🍇🧊", key: "uva-menthol", dualA: "Uva", dualB: "Menthol" },
    { name: "Fresh mint / Mango orange", emoji: "🧊🥭🍊", key: "fresh-mint-mango-orange", dualA: "Fresh mint", dualB: "Mango orange" },
    { name: "Passion fruit / Morango melancia", emoji: "🧊🍉🍓", key: "passion-fruit-morango-melancia", dualA: "Passion fruit", dualB: "Morango melancia" },
  ]},
  { id: "dinnerlady-dual-flavor", brand: "DinnerLady", model: "Dual Flavor", puffs: 50000, puffsLabel: "50 mil puxadas", priceFrom: 220, priceTo: 166, dual: true, form: "dual", flavors: [
    { name: "Uva ice / Mint ice", emoji: "🍇🧊", key: "uva-ice-mint-ice", dualA: "Uva ice", dualB: "Mint ice" },
    { name: "Mint ice / Abacaxi ice", emoji: "🧊🍍", key: "mint-ice-abacaxi-ice", dualA: "Mint ice", dualB: "Abacaxi ice" },
    { name: "Melancia ice / Morango ice", emoji: "🍉🍓", key: "melancia-ice-morango-ice", dualA: "Melancia ice", dualB: "Morango ice" },
    { name: "Melancia ice / Blue mint", emoji: "🍉🧊", key: "melancia-ice-blue-mint", dualA: "Melancia ice", dualB: "Blue mint" },
    { name: "Menthol / Passion fruit ice", emoji: "🧊🧊", key: "menthol-passion-fruit-ice", dualA: "Menthol", dualB: "Passion fruit ice" },
  ]},
  { id: "ignite-v400-mix", brand: "Ignite", model: "V400 Mix", puffs: 40000, puffsLabel: "40 mil puxadas", priceFrom: 199, priceTo: 159, dual: true, form: "dual", flavors: [
    { name: "Uva / Pêssego", emoji: "🍇🍑", key: "uva-pessego", dualA: "Uva", dualB: "Pêssego" },
    { name: "Melancia ice / Cereja ice", emoji: "🍉🍒", key: "melancia-ice-cereja-ice", dualA: "Melancia ice", dualB: "Cereja ice" },
    { name: "Uva ice / Melancia ice", emoji: "🍇🍉", key: "uva-ice-melancia-ice", dualA: "Uva ice", dualB: "Melancia ice" },
    { name: "Melão / Menthol", emoji: "🍈🧊", key: "melao-menthol", dualA: "Melão", dualB: "Menthol" },
    { name: "Icy mint / Pêssego uva", emoji: "🧊🍑🍇", key: "icy-mint-pessego-uva", dualA: "Icy mint", dualB: "Pêssego uva" },
    { name: "Mango ice / Passion fruit guava", emoji: "🥭🧊", key: "mango-ice-passion-fruit-guava", dualA: "Mango ice", dualB: "Passion fruit guava" },
    { name: "Maçã ice / Morango melancia", emoji: "🍎🍉🍓", key: "maca-ice-morango-melancia", dualA: "Maçã ice", dualB: "Morango melancia" },
    { name: "Morango melancia / Aloe grape", emoji: "🍓🍉🧊", key: "morango-melancia-aloe-grape", dualA: "Morango melancia", dualB: "Aloe grape" },
    { name: "Melancia uva ice / Açaí ice", emoji: "🍉🍇", key: "melancia-uva-ice-acai-ice", dualA: "Melancia uva ice", dualB: "Açaí ice" },
    { name: "Abacaxi manga ice / Morango ice", emoji: "🍍🥭🍓", key: "abacaxi-manga-ice-morango-ice", dualA: "Abacaxi manga ice", dualB: "Morango ice" },
    { name: "Blueberry ice / Blackberry raspberry", emoji: "🧊🍒", key: "blueberry-ice-blackberry-raspberry", dualA: "Blueberry ice", dualB: "Blackberry raspberry" },
  ]},
  { id: "elfbar-bc40k", brand: "Elfbar", model: "BC40K", puffs: 40000, puffsLabel: "40 mil puxadas", priceFrom: 185, priceTo: 149, dual: false, form: "box", flavors: [
    { name: "Toasted abacaxi", emoji: "🍍", key: "toasted-abacaxi" },
    { name: "Morango kiwi", emoji: "🍓🥝", key: "morango-kiwi" },
  ]},
  { id: "ignite-v400-ice", brand: "Ignite", model: "V400 ICE", puffs: 40000, puffsLabel: "40 mil puxadas", priceFrom: 189, priceTo: 149, dual: false, form: "cylinder", flavors: [
    { name: "Uva ice", emoji: "🍇", key: "uva-ice" },
    { name: "Mint ice", emoji: "🧊", key: "mint-ice" },
    { name: "Blueberry ice", emoji: "🧊", key: "blueberry-ice" },
    { name: "Blue razz lemon", emoji: "🍋", key: "blue-razz-lemon" },
    { name: "Morango kiwi ice", emoji: "🍓🥝", key: "morango-kiwi-ice" },
    { name: "Morango banana", emoji: "🍓🍌", key: "morango-banana" },
  ]},
  { id: "elfbar-iceking", brand: "Elfbar", model: "Iceking", puffs: 40000, puffsLabel: "40 mil puxadas", priceFrom: 189, priceTo: 149, dual: false, form: "box", flavors: [
    { name: "Uva ice", emoji: "🍇", key: "uva-ice" },
    { name: "Miami mint", emoji: "🧊", key: "miami-mint" },
  ]},
  { id: "ignite-v300-ultra-slim", brand: "Ignite", model: "V300 Ultra Slim", puffs: 30000, puffsLabel: "30 mil puxadas", priceFrom: 189, priceTo: 149, dual: false, form: "ultraslim", flavors: [
    { name: "Uva ice", emoji: "🍇", key: "uva-ice" },
    { name: "Morango ice", emoji: "🍓", key: "morango-ice" },
    { name: "Melancia ice", emoji: "🍉", key: "melancia-ice" },
  ]},
  { id: "elfbar-te30k", brand: "Elfbar", model: "TE30K", puffs: 30000, puffsLabel: "30 mil puxadas", priceFrom: 180, priceTo: 144, dual: false, form: "box", flavors: [
    { name: "Uva", emoji: "🍇", key: "uva" },
    { name: "Morango ice", emoji: "🍓", key: "morango-ice" },
    { name: "Melancia ice", emoji: "🍉", key: "melancia-ice" },
    { name: "Blueberry ice", emoji: "🧊", key: "blueberry-ice" },
    { name: "Morango pêssego melão", emoji: "🍑🍓🍈", key: "morango-pessego-melao" },
  ]},
  { id: "ignite-frozen-20k", brand: "Ignite", model: "Frozen 20K", puffs: 20000, puffsLabel: "20 mil puxadas", priceFrom: 159, priceTo: 139, dual: false, form: "cylinder", flavors: [
    { name: "Uva ice", emoji: "🍇", key: "uva-ice" },
    { name: "Morango ice", emoji: "🍓", key: "morango-ice" },
    { name: "Melancia ice", emoji: "🍉", key: "melancia-ice" },
    { name: "Abacaxi ice", emoji: "🍍", key: "abacaxi-ice" },
    { name: "Morango kiwi", emoji: "🍓🥝", key: "morango-kiwi" },
    { name: "Morango banana", emoji: "🍓🍌", key: "morango-banana" },
  ]},
  { id: "elfbar-duke", brand: "Elfbar", model: "Duke", puffs: 35000, puffsLabel: "35 mil puxadas", priceFrom: 170, priceTo: 139, dual: false, form: "box", flavors: [
    { name: "Icy mint", emoji: "🧊", key: "icy-mint" },
    { name: "Uva ice", emoji: "🍇", key: "uva-ice" },
    { name: "Melancia ice", emoji: "🍉", key: "melancia-ice" },
    { name: "Morango kiwi ice", emoji: "🍓🥝", key: "morango-kiwi-ice" },
    { name: "Bubbaloo tutti-frutti", emoji: "🍬", key: "bubbaloo-tutti-frutti" },
    { name: "Pêssego manga melancia", emoji: "🍑🥭🍉", key: "pessego-manga-melancia" },
  ]},
  { id: "lost-mary-35k", brand: "Lost Mary", model: "35K", puffs: 35000, puffsLabel: "35 mil puxadas", priceFrom: 169, priceTo: 129, dual: false, form: "box", flavors: [
    { name: "Summer orange", emoji: "🍊", key: "summer-orange" },
    { name: "Melancia ice", emoji: "🍉", key: "melancia-ice" },
    { name: "Morango ice", emoji: "🍓", key: "morango-ice" },
    { name: "Blue razz ice", emoji: "🧊", key: "blue-razz-ice" },
    { name: "Maçã verde ice", emoji: "🍏", key: "maca-verde-ice" },
    { name: "Morango kiwi", emoji: "🍓🥝", key: "morango-kiwi" },
    { name: "Grapefruit guava", emoji: "🍇", key: "grapefruit-guava" },
  ]},
  { id: "ignite-v155-ultra-slim", brand: "Ignite", model: "V155 Ultra Slim", puffs: 15500, puffsLabel: "15,5 mil puxadas", priceFrom: 169, priceTo: 129, dual: false, form: "ultraslim", flavors: [
    { name: "Icy mint", emoji: "🧊", key: "icy-mint" },
    { name: "Melancia ice", emoji: "🍉", key: "melancia-ice" },
    { name: "Morango kiwi", emoji: "🍓🥝", key: "morango-kiwi" },
    { name: "Morango melancia", emoji: "🍓🍉", key: "morango-melancia" },
    { name: "Kiwi passion fruit guava", emoji: "🥝", key: "kiwi-passion-fruit-guava" },
  ]},
  { id: "dinnerlady-luma", brand: "DinnerLady", model: "Luma", puffs: 20000, puffsLabel: "20 mil puxadas", priceFrom: 160, priceTo: 124, dual: false, form: "box", flavors: [
    { name: "Uva ice", emoji: "🍇", key: "uva-ice" },
    { name: "Icy mint", emoji: "🧊", key: "icy-mint" },
    { name: "Melancia ice", emoji: "🍉", key: "melancia-ice" },
  ]},
  { id: "ignite-v80", brand: "Ignite", model: "V80", puffs: 8000, puffsLabel: "8 mil puxadas", priceFrom: 159, priceTo: 119, dual: false, form: "cylinder", flavors: [
    { name: "Morango ice", emoji: "🍓", key: "morango-ice" },
    { name: "Morango kiwi", emoji: "🍓🥝", key: "morango-kiwi" },
    { name: "Melancia ice", emoji: "🍉", key: "melancia-ice" },
    { name: "Blue razz lemon", emoji: "🧊", key: "blue-razz-lemon" },
  ]},
  { id: "elfbar-bc15k", brand: "Elfbar", model: "BC15K", puffs: 15000, puffsLabel: "15 mil puxadas", priceFrom: 134, priceTo: 114, dual: false, form: "box", flavors: [
    { name: "Uva", emoji: "🍇", key: "uva" },
    { name: "Morango ice", emoji: "🍓", key: "morango-ice" },
    { name: "Mango magic", emoji: "🥭", key: "mango-magic" },
    { name: "Americano ice", emoji: "☕️", key: "americano-ice" },
    { name: "Maçã verde ice", emoji: "🍏", key: "maca-verde-ice" },
  ]},
];

/* Paleta sabor → gradiente. Ordem importa: a primeira regra cujo `match`
   aparece na chave do sabor vence, então o específico vem antes do genérico. */
const PALETTE = [
  { match: "morango-kiwi", from: "#FF2D55", to: "#7FE83C", accent: "#C4FF6B" },
  { match: "morango-melancia", from: "#FF1F5A", to: "#FF6FA8", accent: "#FFA8C8" },
  { match: "morango-banana", from: "#FF2D55", to: "#FFD93D", accent: "#FFEE8A" },
  { match: "morango-pessego", from: "#FF3D6E", to: "#FFB07C", accent: "#FFD0B8" },
  { match: "melancia-cereja", from: "#FF6B8B", to: "#E4003A", accent: "#FFA3BC" },
  { match: "banana-cereja", from: "#FFD93D", to: "#FF2E4D", accent: "#FF9AA8" },
  { match: "abacaxi-kiwi", from: "#FFE24B", to: "#62D62A", accent: "#CBFF5E" },
  { match: "abacaxi-com-manga", from: "#FFE73D", to: "#FF6B00", accent: "#FFD08A" },
  { match: "kiwi-com-acai", from: "#9BE15D", to: "#7A3FF2", accent: "#C9A6FF" },
  { match: "kiwi-passion", from: "#7CFF4D", to: "#FFB627", accent: "#DBFF7A" },
  { match: "mango-passion", from: "#FF9F1C", to: "#FF3D7F", accent: "#FFD08A" },
  { match: "passion-fruit-guava", from: "#FFB01F", to: "#FF4D8D", accent: "#FFD4A8" },
  { match: "passion-fruit-sour", from: "#FFC72E", to: "#A3E635", accent: "#FFE28A" },
  { match: "grapefruit-guava", from: "#FF7A5C", to: "#FF2E7E", accent: "#FFB3C9" },
  { match: "blackberry-raspberry", from: "#7B2FF7", to: "#FF2E63", accent: "#C77DFF" },
  { match: "blue-razz-lemon", from: "#2D9BFF", to: "#FFE93D", accent: "#9BE7FF" },
  { match: "blue-razz", from: "#1F6FFF", to: "#FF3D9A", accent: "#7FC4FF" },
  { match: "blue-mint", from: "#2FD8FF", to: "#00FFC2", accent: "#A5FFF0" },
  { match: "blueberry-lemonade", from: "#4C6FFF", to: "#FFE84D", accent: "#A9C4FF" },
  { match: "aloe-grape", from: "#7CE495", to: "#9B5DE5", accent: "#C6FFD8" },
  { match: "white-grape", from: "#EAF7A8", to: "#A3D93D", accent: "#F4FFC2" },
  { match: "double-apple", from: "#34E36F", to: "#FF2E4D", accent: "#9DFFC0" },
  { match: "sour-apple", from: "#A8FF35", to: "#35D93F", accent: "#D6FF7A" },
  { match: "maca-verde", from: "#6EF25A", to: "#17B978", accent: "#B4FF8F" },
  { match: "miami-mint", from: "#2BFFCB", to: "#29B6FF", accent: "#A6FFEA" },
  { match: "icy-mint", from: "#7DF9FF", to: "#24D2FF", accent: "#C9FBFF" },
  { match: "triple-mint", from: "#5CFFDD", to: "#1FA8FF", accent: "#B6FFF2" },
  { match: "fresh-mint", from: "#4DFFC4", to: "#0FC9C9", accent: "#B3FFE9" },
  { match: "grapefruit", from: "#FF8A5C", to: "#FF2E63", accent: "#FFB89B" },
  { match: "blueberry", from: "#3B82F6", to: "#8B5CF6", accent: "#A5C8FF" },
  { match: "dragon-fruit", from: "#FF2E9E", to: "#A020F0", accent: "#FF9BE0" },
  { match: "passion-fruit", from: "#FFC72E", to: "#FF5E1F", accent: "#FFE28A" },
  { match: "toasted-abacaxi", from: "#FFC04B", to: "#D97706", accent: "#FFE0A0" },
  { match: "abacaxi", from: "#FFE73D", to: "#FFB300", accent: "#FFF48A" },
  { match: "mango-magic", from: "#FFC12E", to: "#FF4D8D", accent: "#FFE39B" },
  { match: "summer-orange", from: "#FFB01F", to: "#FF5400", accent: "#FFD48A" },
  { match: "ultimate-melon", from: "#FFA860", to: "#C6F06B", accent: "#FFE9B8" },
  { match: "triple-melon", from: "#FF9F5A", to: "#B6F06B", accent: "#FFE3A8" },
  { match: "bubbaloo", from: "#FF6BC1", to: "#FF2E7E", accent: "#FFB8E0" },
  { match: "tutti-frutti", from: "#FF2E9E", to: "#FFD93D", accent: "#FF9BE0" },
  { match: "americano", from: "#E0A45E", to: "#A15C2B", accent: "#FFD9A8" },
  { match: "cool-menthol", from: "#5CFFD0", to: "#00A8C2", accent: "#B3FFEC" },
  { match: "uva", from: "#A855F7", to: "#6D2BE0", accent: "#E0B3FF" },
  { match: "grape", from: "#C084FC", to: "#8B2FE8", accent: "#E9C6FF" },
  { match: "morango", from: "#FF2E63", to: "#D91E5B", accent: "#FF9DBE" },
  { match: "strawberry", from: "#FF4D6D", to: "#E01E5A", accent: "#FFAABF" },
  { match: "melancia", from: "#FF4D7A", to: "#3DDC84", accent: "#FF9FC0" },
  { match: "watermelon", from: "#FF5C8D", to: "#4AE58A", accent: "#FFB3CE" },
  { match: "kiwi", from: "#A7F432", to: "#57C21B", accent: "#D9FF7A" },
  { match: "cereja", from: "#FF3355", to: "#E4003A", accent: "#FF8DA1" },
  { match: "cherry", from: "#FF4059", to: "#D10036", accent: "#FF97A8" },
  { match: "banana", from: "#FFE23D", to: "#FFC300", accent: "#FFF48F" },
  { match: "acai", from: "#B14BFF", to: "#6A1FD0", accent: "#D9A6FF" },
  { match: "guava", from: "#FF5C8A", to: "#FF2E9E", accent: "#FFB0D6" },
  { match: "manga", from: "#FFB01F", to: "#FF6B00", accent: "#FFDD8A" },
  { match: "mango", from: "#FFC12E", to: "#FF7A00", accent: "#FFE39B" },
  { match: "pessego", from: "#FFB07C", to: "#FF6A3D", accent: "#FFD6BA" },
  { match: "peach", from: "#FFC08A", to: "#FF7A45", accent: "#FFE0C2" },
  { match: "maca", from: "#58E86A", to: "#B6FF3D", accent: "#DBFF8A" },
  { match: "apple", from: "#3DDC6E", to: "#A8F03C", accent: "#CFFF7A" },
  { match: "melao", from: "#FFA860", to: "#FFDD87", accent: "#FFE9B8" },
  { match: "melon", from: "#FF9F5A", to: "#C6F06B", accent: "#FFE3A8" },
  { match: "lemon", from: "#FFF23D", to: "#FFDD00", accent: "#FFFB8F" },
  { match: "laranja", from: "#FF9F1C", to: "#FF5400", accent: "#FFC875" },
  { match: "orange", from: "#FFAE1F", to: "#FF6200", accent: "#FFD48A" },
  { match: "aloe", from: "#7CFFB2", to: "#29D8A0", accent: "#C2FFDF" },
  { match: "blackberry", from: "#6C2BD9", to: "#B14BFF", accent: "#C9A0FF" },
  { match: "raspberry", from: "#FF3D8F", to: "#E01B6A", accent: "#FF9BC7" },
  { match: "sour", from: "#E1FF3D", to: "#A3E635", accent: "#EFFF8A" },
  { match: "menthol", from: "#3DFFB0", to: "#00C2A8", accent: "#A8FFE0" },
  { match: "mint", from: "#4DFFCB", to: "#12B8FF", accent: "#B0FFE8" },
  { match: "ice", from: "#7DE8FF", to: "#2E9BFF", accent: "#BFF3FF" },
];

const PALETTE_FALLBACK = { from: "#A855F7", to: "#F038FF", accent: "#E3B0FF" };

/* Cor da marca — usada no selo e no anel do device. */
const BRAND_COLORS = {
  Ignite: "#FF5A1F",
  Elfbar: "#22D3EE",
  DinnerLady: "#F472B6",
  Oxbar: "#A78BFA",
  BlackSheep: "#94A3B8",
  "Lost Mary": "#FBBF24",
};
